# .github/PULL_REQUEST_TEMPLATE/pull_request.yml

name: Pull Request
about: Submit a pull request to help us improve
title: '[PR] '

body:
  - type: markdown
    label: 🟠 작업 내용 이슈 번호
    required: true

  - name: checklist
    about: Checklist
    type: checklist
    options:
      - ISSUE FEATURE 100% 완료
      - ISSUE FEATURE 완료 후 추가 작업 필요

  - type: textarea
    label: 🔴 주의 사항
